name: wp-tools
recipe: laravel
config:
  php: '8.0'
  composer_version: 2
  webroot: public
  database: mysql:8.0
services:
  appserver:
    xdebug: true
    config:
      php: .vscode/php.ini
  node:
    type: node:14
tooling:
  node:
    service: node
  npx:
    service: node
  yarn:
    service: node
